bf16: true
cutoff_len: 4096
dataset: 4dataset
dataset_dir: /root/LLaMA-Factory/data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_config.json
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 32
lora_dropout: 0
lora_rank: 8
lora_target: all
loraplus_lr_ratio: 16
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /root/autodl-tmp/DeepSeek_Qwen7B
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/Custom/lora/4dataset
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
warmup_steps: 0
